/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/reminders/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Route */
        post: operations["preview_route_api_v1_reminders_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Route */
        get: operations["list_route_api_v1_reminders_get"];
        put?: never;
        /** Create Route */
        post: operations["create_route_api_v1_reminders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/{reminder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route */
        get: operations["get_route_api_v1_reminders__reminder_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Route */
        patch: operations["edit_route_api_v1_reminders__reminder_id__patch"];
        trace?: never;
    };
    "/api/v1/reminders/{reminder_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Route */
        post: operations["cancel_route_api_v1_reminders__reminder_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications Route */
        get: operations["notifications_route_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread Route */
        get: operations["unread_route_api_v1_notifications_unread_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read All Route */
        post: operations["read_all_route_api_v1_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read One Route */
        post: operations["read_one_route_api_v1_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification-settings/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Destination */
        get: operations["get_destination_api_v1_notification_settings_whatsapp_get"];
        /** Put Destination */
        put: operations["put_destination_api_v1_notification_settings_whatsapp_put"];
        post?: never;
        /** Delete Destination */
        delete: operations["delete_destination_api_v1_notification_settings_whatsapp_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Route */
        post: operations["register_route_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Route */
        post: operations["login_route_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Route */
        post: operations["refresh_route_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Route */
        post: operations["logout_route_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me Route */
        get: operations["me_route_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Credentials */
        Credentials: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** DestinationInput */
        DestinationInput: {
            /** Phone */
            phone: string;
            /**
             * Consent
             * @constant
             */
            consent: true;
        };
        /** DestinationPublic */
        DestinationPublic: {
            /** Available */
            available: boolean;
            /** Active */
            active: boolean;
            /** Masked Number */
            masked_number: string | null;
            /** Opted In At */
            opted_in_at: string | null;
            /** Consent Text Version */
            consent_text_version: string | null;
            /** Consent Text */
            consent_text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NotificationPage */
        NotificationPage: {
            /** Items */
            items: components["schemas"]["NotificationPublic"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** NotificationPublic */
        NotificationPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Reminder Id
             * Format: uuid
             */
            reminder_id: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read At */
            read_at: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ReminderCreate */
        ReminderCreate: {
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Local Time */
            local_time: string;
            /** Timezone */
            timezone: string;
            /** Message */
            message: string;
            /**
             * Send Whatsapp
             * @default false
             */
            send_whatsapp: boolean;
        };
        /** ReminderPage */
        ReminderPage: {
            /** Items */
            items: components["schemas"]["ReminderPublic"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ReminderPatch */
        ReminderPatch: {
            /** Expected Version */
            expected_version: number;
            /** Message */
            message?: string | null;
            /** Local Date */
            local_date?: string | null;
            /** Local Time */
            local_time?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Send Whatsapp */
            send_whatsapp?: boolean | null;
        };
        /** ReminderPublic */
        ReminderPublic: {
            /**
             * Scheduled At Utc
             * Format: date-time
             */
            scheduled_at_utc: string;
            /** Local Date */
            local_date: string;
            /** Local Time */
            local_time: string;
            /** Timezone */
            timezone: string;
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "exact" | "gap_forward" | "overlap_later";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Message */
            message: string;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "processing" | "fired" | "canceled";
            /** Send Whatsapp */
            send_whatsapp: boolean;
            /** Whatsapp Status */
            whatsapp_status: ("pending" | "sending" | "accepted" | "failed" | "unknown" | "canceled") | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fired At */
            fired_at: string | null;
            /** Canceled At */
            canceled_at: string | null;
        };
        /** ScheduleInput */
        ScheduleInput: {
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Local Time */
            local_time: string;
            /** Timezone */
            timezone: string;
        };
        /** SchedulePreview */
        SchedulePreview: {
            /**
             * Scheduled At Utc
             * Format: date-time
             */
            scheduled_at_utc: string;
            /** Local Date */
            local_date: string;
            /** Local Time */
            local_time: string;
            /** Timezone */
            timezone: string;
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "exact" | "gap_forward" | "overlap_later";
        };
        /** TokenPair */
        TokenPair: {
            user: components["schemas"]["UserPublic"];
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            /**
             * Expires In
             * @default 900
             */
            expires_in: number;
        };
        /** UnreadCount */
        UnreadCount: {
            /** Count */
            count: number;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionInput */
        VersionInput: {
            /** Expected Version */
            expected_version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    preview_route_api_v1_reminders_preview_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulePreview"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    list_route_api_v1_reminders_get: {
        parameters: {
            query?: {
                status?: "upcoming" | "fired" | "canceled";
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderPage"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    create_route_api_v1_reminders_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderPublic"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    get_route_api_v1_reminders__reminder_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                reminder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderPublic"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    edit_route_api_v1_reminders__reminder_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                reminder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderPublic"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    cancel_route_api_v1_reminders__reminder_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                reminder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderPublic"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    notifications_route_api_v1_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    unread_route_api_v1_notifications_unread_count_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCount"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    read_all_route_api_v1_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    read_one_route_api_v1_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    get_destination_api_v1_notification_settings_whatsapp_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_destination_api_v1_notification_settings_whatsapp_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DestinationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_destination_api_v1_notification_settings_whatsapp_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_route_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Problem response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    login_route_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    refresh_route_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Problem response */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    logout_route_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
        };
    };
    me_route_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Instance */
                        instance: string;
                        /** Traceid */
                        traceId: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
